# Generated by Django 5.2.3 on 2025-06-25 14:30

import django.db.models.deletion
import myq.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myq', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='original_filename',
            field=models.CharField(default='', max_length=255, verbose_name='元のファイル名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所有者'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=myq.models.upload_to_uuid_path, verbose_name='画像'),
        ),
    ]
