# Generated by Django 5.2.3 on 2025-06-25 14:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myq', '0002_photo_original_filename_photo_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
