# Generated by Django 5.2.3 on 2025-06-25 15:24

import django.db.models.deletion
import myq.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myq', '0003_photo_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentedPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(upload_to=myq.models.upload_to_uuid_path, verbose_name='切り抜き画像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('original_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmented_images', to='myq.photo')),
            ],
        ),
    ]
