# Generated by Django 5.2.3 on 2025-06-25 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myq', '0004_segmentedphoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentedphoto',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所有者'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='segmentedphoto',
            name='original_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segmented_images', to='myq.photo', verbose_name='元の画像'),
        ),
    ]
