# Generated by Django 5.2.3 on 2025-10-14 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myq', '0006_autologintoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=512, verbose_name='アクセスURL')),
                ('method', models.CharField(max_length=10, verbose_name='メソッド')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IPアドレス')),
                ('user_agent', models.TextField(blank=True, verbose_name='ユーザーエージェント')),
                ('referer', models.TextField(blank=True, verbose_name='リファラ')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='アクセス時刻')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'アクセスログ',
                'verbose_name_plural': 'アクセスログ一覧',
                'ordering': ['-timestamp'],
            },
        ),
    ]
