# Generated by Django 5.2.3 on 2025-10-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myq', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='needupdate',
            field=models.BooleanField(default=False),
        ),
    ]
