# Generated by Django 6.0.5 on 2026-05-19 02:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myq', '0009_profile_needupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentedphoto',
            name='albedo',
            field=models.CharField(default='#FFFFFF', help_text='Hex color code, e.g., #FFAA00', max_length=7, verbose_name='アルベド (RGB)'),
        ),
        migrations.AddField(
            model_name='segmentedphoto',
            name='diffuse_reflectance',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='拡散反射率'),
        ),
        migrations.AddField(
            model_name='segmentedphoto',
            name='specular_reflectance',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='鏡面反射率'),
        ),
    ]
