# Generated by Django 6.0.5 on 2026-05-29 00:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myq', '0010_segmentedphoto_albedo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='albedo',
            field=models.CharField(default='#FFFFFF', help_text='Hex color code, e.g., #FFAA00', max_length=7, validators=[django.core.validators.RegexValidator(regex='^#[0-9A-Fa-f]{6}$')], verbose_name='アルベド'),
        ),
        migrations.AddField(
            model_name='photo',
            name='diffuse_reflectance',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='拡散反射率'),
        ),
        migrations.AddField(
            model_name='photo',
            name='specular_reflectance',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='鏡面反射率'),
        ),
        migrations.AlterField(
            model_name='segmentedphoto',
            name='albedo',
            field=models.CharField(default='#FFFFFF', help_text='Hex color code, e.g., #FFAA00', max_length=7, validators=[django.core.validators.RegexValidator(regex='^#[0-9A-Fa-f]{6}$')], verbose_name='アルベド'),
        ),
    ]
