# Generated by Django 6.0.5 on 2026-05-29 05:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myq', '0011_photo_albedo_photo_diffuse_reflectance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='diffuse_reflectance',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='specular_reflectance',
        ),
        migrations.RemoveField(
            model_name='segmentedphoto',
            name='diffuse_reflectance',
        ),
        migrations.RemoveField(
            model_name='segmentedphoto',
            name='specular_reflectance',
        ),
        migrations.AddField(
            model_name='photo',
            name='metalness',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='metalness'),
        ),
        migrations.AddField(
            model_name='photo',
            name='roughness',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='roughness'),
        ),
        migrations.AddField(
            model_name='segmentedphoto',
            name='metalness',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='metalness'),
        ),
        migrations.AddField(
            model_name='segmentedphoto',
            name='roughness',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='roughness'),
        ),
    ]
