# Generated by Django 6.0.5 on 2026-05-29 10:06

import django.core.validators
import django.db.models.deletion
import myq.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myq', '0012_remove_photo_diffuse_reflectance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=myq.models.upload_to_photo_path, verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='segmentedphoto',
            name='image',
            field=models.ImageField(upload_to=myq.models.upload_to_segmented_path, verbose_name='切り抜き画像'),
        ),
        migrations.CreateModel(
            name='SegmentedPhoto2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('segment_npy', models.FileField(blank=True, null=True, upload_to=myq.models.upload_to_npy_path)),
                ('image', models.ImageField(blank=True, null=True, upload_to=myq.models.upload_to_segmented_path, verbose_name='切り抜き画像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('roughness', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='roughness')),
                ('metalness', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='metalness')),
                ('albedo', models.CharField(default='#FFFFFF', help_text='Hex color code, e.g., #FFAA00', max_length=7, validators=[django.core.validators.RegexValidator(regex='^#[0-9A-Fa-f]{6}$')], verbose_name='アルベド')),
                ('original_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segmented_images2', to='myq.photo', verbose_name='元の画像')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
        ),
    ]
