# Generated by Django 6.1 on 2026-08-20 06:32

import myq.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myq', '0013_alter_photo_image_alter_segmentedphoto_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesslog',
            options={'ordering': ('-timestamp',), 'verbose_name': 'アクセスログ', 'verbose_name_plural': 'アクセスログ一覧'},
        ),
        migrations.AddField(
            model_name='segmentedphoto',
            name='rendered_image',
            field=models.ImageField(blank=True, null=True, upload_to=myq.models.upload_to_rendered_path, verbose_name='質感再現画像'),
        ),
    ]
